import { Activity, BookOpen, CalendarDays, Check, Clapperboard, FileText, FolderPlus, ListFilter, ListVideo, LoaderCircle, Play, RefreshCcw, RotateCcw, Save, Search, Sparkles, Trash2, UserRound, Volume2, WandSparkles, X } from "lucide-react";

import { BackendStatusBanner } from "./BackendStatusBanner";
import { BatchActionBar } from "./BatchActionBar";
import { CandidateHistory } from "./CandidateHistory";
import { ExportsPanel } from "./ExportsPanel";
import { KeyframeStrip } from "./KeyframeStrip";
import { LogViewerPanel } from "./LogViewerPanel";
import { ModelCatalogPanel } from "./ModelCatalogPanel";
import { SettingCheck, SettingNumber, SettingText } from "./SettingsFields";
import { SettingsPanel } from "./SettingsPanel";
import { QueuePanel } from "./QueuePanel";
import { SystemPanel } from "./SystemPanel";
import type { CandidateFilter, CandidateSort } from "../hooks/useCandidates";
import type { SerialCutsController } from "../hooks/useSerialCutsController";
import type { Candidate, StoryArc } from "../types";
import { arcNarration, editFromCandidate, formatArcFormat, formatBytes, formatClock, formatElapsed, formatRange, identityMethodLabel, previewCropOffset, SILERO_VOICES, splitLines, stageLabel, statusLabel, voiceLabel } from "../utils";

type AppViewProps = {
  controller: SerialCutsController;
};

export function AppView({ controller }: AppViewProps) {
  const { rootPath, setRootPath, seasons, checks, queue, settings, diagnostics, cacheInfo, exports, selectedEpisodeId, selectedCandidate, edits, candidateFilter, setCandidateFilter, candidateSort, setCandidateSort, candidateSearch, setCandidateSearch, candidateMomentType, setCandidateMomentType, candidateMinScore, setCandidateMinScore, visibleCandidates, momentTypes, selectedEdit, setCandidateEdit, subtitles, setSubtitles, subtitleBusy, candidateQuality, episodeQuality, subtitleQuality, jobStages, previewUrl, previewBusy, message, videoTime, storyContext, setStoryContext, projectDiagnostics, setArcSeasonId, arcTitle, setArcTitle, arcPrompt, setArcPrompt, arcFormat, setArcFormat, arcCharacterId, setArcCharacterId, arcMaxSegments, setArcMaxSegments, arcMaxDuration, setArcMaxDuration, arcRenderBusy, setWorkflowArcId, arcTransition, setArcTransition, arcIncludeNarration, setArcIncludeNarration, arcNarrationMode, setArcNarrationMode, seasonSearch, setSeasonSearch, searchResults, scriptPrompt, setScriptPrompt, characters, speakerLabels, speakerIdentities, episodeOutline, characterName, setCharacterName, characterDescription, setCharacterDescription, characterPhotos, videoRef, backgroundVideoRef, refresh, runSystemCheck, importSeason, enqueueSeason, enqueueEpisode, deleteEpisode, deleteSeason, deleteJob, runQueueNext, setPaused, cancelJob, retryJob, retryJobStage, runDirectStage, loadJobStages, loadCandidates, saveStoryContext, assignSpeaker, regenerateStoryCandidates, createCharacter, deleteCharacter, readCharacterPhotos, addCharacterPhotos, deleteCharacterPhoto, setCharacterNarrationVoice, identifyCharacters, openCandidate, reviewCandidate, autoCrop, chooseCrop, saveSubtitles, resetSubtitles, autoSplitSubtitles, renderCandidate, renderPreview, createStoryArc, rebuildStoryArc, deleteStoryArc, renderStoryArc, enqueueStoryArcRender, saveArcMeta, saveArcSegment, moveArcSegment, removeArcSegment, runSeasonSearch, addSearchResultToArc, createVideoScriptForArc, synthesizeNarration, createPublishingPlanForArc, createPublishingPackageForPlan, refreshProjectDiagnostics, openArcSegment, mergeCharacter, autoExport, saveSettings, clearCache, patchArcLocal, patchArcSegmentLocal, patchSettings, updateSubtitle, onVideoTimeUpdate, isEpisodeBusy, activeSubtitle, arcSeason, arcCharacters, visibleStoryArcs, workflowArc, workflowScripts, workflowPublishing, batchSelection, toggleBatchCandidate, setBatchCandidates, clearBatchSelection, batchReviewCandidates, batchRenderCandidates } = controller;

  return <main className="app-shell">
    <BackendStatusBanner />
    <section className="topbar"><div><h1>SerialCuts</h1><p>Локальная подготовка вертикальных клипов из серий</p></div><button className="icon-button" title="Обновить всё" onClick={() => refresh()}><RefreshCcw size={20} /></button></section>
    {message && <p className="notice" role="status">{message}</p>}
    <section className="grid dashboard-grid">
      <div className="panel"><div className="panel-title"><FolderPlus size={19} /><h2>Сезоны</h2></div><div className="path-row"><input value={rootPath} onChange={(event) => setRootPath(event.target.value)} placeholder="D:\Сериалы\Название\Сезон 1" /><button onClick={importSeason}>Добавить</button></div><div className="season-list">
        {seasons.map((season) => <article className="season" key={season.id}><div><strong>{season.title}</strong><small>{season.episodes.length} серий</small></div><button onClick={() => enqueueSeason(season.id, false)}>Анализ сезона</button><button onClick={() => enqueueSeason(season.id, true)}><Sparkles size={16} /> Auto</button><button className="text-button danger" title="Удалить сезон" onClick={() => deleteSeason(season)}><Trash2 size={15} /></button></article>)}
        {!seasons.length && <p className="empty">Добавьте папку с сериями — исходные файлы останутся без изменений.</p>}
      </div></div>
      <QueuePanel queue={queue} jobStages={jobStages} onRunNext={runQueueNext} onSetPaused={setPaused} onLoadStages={loadJobStages} onCancel={cancelJob} onRetry={retryJob} onRetryStage={retryJobStage} onDelete={deleteJob} />
    </section>

    <section className="panel section-gap"><div className="panel-title"><ListVideo size={19} /><h2>Серии</h2></div><div className="episodes">{seasons.flatMap((season) => season.episodes).map((episode) => { const busy = isEpisodeBusy(episode.id); return <article className="episode" key={episode.id}><div><strong>{episode.file_name}</strong><small>{busy ? "Обрабатывается в очереди" : stageLabel(episode.stage)}</small></div><span>{formatBytes(episode.size_bytes)}</span><span>{episode.width && episode.height ? `${episode.width}×${episode.height}` : "без метаданных"}</span><button disabled={busy} onClick={() => enqueueEpisode(episode)}>В очередь</button><button className="secondary" disabled={busy} onClick={() => runDirectStage(episode, "media")}>Только медиа</button><button className="secondary" disabled={busy} onClick={() => runDirectStage(episode, "candidates")}>Только кандидаты</button><button onClick={() => loadCandidates(episode.id)}>Открыть</button><button className="secondary" disabled={busy} onClick={() => autoExport(episode.id)}>Auto export</button><button className="text-button danger" disabled={busy} title="Удалить серию" onClick={() => deleteEpisode(episode)}><Trash2 size={15} /></button></article>; })}</div></section>

    <section className="story-arc-workspace section-gap">
      <div className="panel"><div className="panel-title"><BookOpen size={19} /><h2>Сюжетные видео</h2><span className="badge">{visibleStoryArcs.length}</span></div><div className="arc-form"><label><span>Сезон</span><select value={arcSeason?.id ?? ""} onChange={(event) => setArcSeasonId(Number(event.target.value) || null)}>{seasons.map((season) => <option key={season.id} value={season.id}>{season.title}</option>)}</select></label><label><span>Формат</span><select value={arcFormat} onChange={(event) => setArcFormat(event.target.value as StoryArc["output_format"])}><option value="single_short">Один Shorts</option><option value="shorts_series">Серия Shorts</option><option value="story_video">Видео 2–10 мин</option><option value="long_video">Длинное видео</option></select></label><label><span>Персонаж</span><select value={arcCharacterId ?? ""} onChange={(event) => setArcCharacterId(Number(event.target.value) || null)}><option value="">Без персонажа</option>{arcCharacters.map((character) => <option key={character.id} value={character.id}>{character.name}</option>)}</select></label><SettingNumber title="Частей" hint="Сколько фрагментов попадёт в план." value={arcMaxSegments} min={1} max={40} onChange={setArcMaxSegments} /><SettingNumber title="Лимит, сек." hint="Суммарная длительность монтажного плана." value={arcMaxDuration} min={15} max={7200} onChange={setArcMaxDuration} /><SettingText title="Название" hint="Можно оставить пустым." value={arcTitle} onChange={setArcTitle} /><label className="setting-field setting-field-wide"><span>Запрос к арке</span><textarea rows={3} value={arcPrompt} onChange={(event) => setArcPrompt(event.target.value)} placeholder="Например: как герой узнал правду об отце, развитие отношений, вся линия конфликта…" /><small>План строится из уже найденных кандидатов сезона.</small></label><button disabled={!arcSeason} onClick={createStoryArc}><Sparkles size={16} /> Создать план</button></div></div>
      <div className="panel"><div className="panel-title"><Clapperboard size={19} /><h2>Монтажные планы</h2></div><div className="arc-list">{visibleStoryArcs.map((arc) => { const latestExport = arc.exports[0]; const narration = arcNarration(arc); return <article className="arc-card" key={arc.id}><div className="arc-head"><div><strong>{arc.title}</strong><small>{formatArcFormat(arc.output_format)} · {formatElapsed(Math.round(arc.total_duration_seconds))}{arc.target_character_name ? ` · ${arc.target_character_name}` : ""}</small></div><div><button className="text-button" onClick={() => rebuildStoryArc(arc.id)}>Пересобрать</button><button className="text-button danger" onClick={() => deleteStoryArc(arc.id)}>Удалить</button></div></div>{arc.prompt && <p>{arc.prompt}</p>}<div className="arc-actions"><button disabled={arcRenderBusy === arc.id || !arc.segments.length} onClick={() => renderStoryArc(arc, true)}>{arcRenderBusy === arc.id ? <LoaderCircle className="spinner" size={16} /> : <Clapperboard size={16} />} Рендер плана</button><button className="secondary" disabled={arcRenderBusy === arc.id || !arc.segments.length} onClick={() => renderStoryArc(arc, false)}>Без субтитров</button></div>{latestExport && <div className="arc-export"><video controls preload="none" src={`/api/story-arc-exports/${latestExport.id}/file`} /><small title={latestExport.output_path}>{latestExport.segment_count} частей · {latestExport.preset_name} · {latestExport.transition_style} · {latestExport.narration_included ? "с озвучкой" : "без озвучки"} · {statusLabel(latestExport.status)} · {latestExport.output_path}</small></div>}{narration.length > 0 && <details className="arc-narration"><summary>Текст озвучки от лица героя</summary>{narration.map((line) => <p key={line.order}><strong>{line.order}.</strong> {line.text}</p>)}</details>}<ol className="arc-segments">{arc.segments.map((segment) => <li key={segment.id}><button onClick={() => openArcSegment(segment)}><span>{segment.sort_order}</span><strong>{segment.title}</strong><small>{segment.episode_file_name} · {formatRange(segment.start_time, segment.end_time)} · {segment.role ?? "часть"}{segment.candidate_score != null ? ` · score ${segment.candidate_score}` : ""}</small></button></li>)}</ol></article>; })}{!visibleStoryArcs.length && <p className="empty">Когда в сезоне появятся кандидаты, здесь можно собрать арку из нескольких серий.</p>}</div></div>
    </section>

    {selectedEpisodeId && storyContext && <section className="story-dashboard section-gap">
      <div className="panel story-panel"><div className="panel-title"><BookOpen size={19} /><h2>Сюжетный контекст</h2><span className="badge">{storyContext.candidate_mode === "story" ? "Связный пересказ" : "Лучшие моменты"}</span></div>
        <div className="story-mode"><button className={storyContext.candidate_mode === "highlights" ? "" : "secondary"} onClick={() => setStoryContext({ ...storyContext, candidate_mode: "highlights" })}>Лучшие моменты</button><button className={storyContext.candidate_mode === "story" ? "" : "secondary"} onClick={() => setStoryContext({ ...storyContext, candidate_mode: "story" })}>Сюжет серии</button></div>
        <label className="story-field"><span>Общая суть сезона</span><textarea rows={4} value={storyContext.season_context} onChange={(event) => setStoryContext({ ...storyContext, season_context: event.target.value })} placeholder="Главные персонажи, отношения, общая история и тон сезона…" /></label>
        <label className="story-field"><span>Суть этой серии</span><textarea rows={4} value={storyContext.episode_summary} onChange={(event) => setStoryContext({ ...storyContext, episode_summary: event.target.value })} placeholder="Завязка, конфликт, важный поворот и итог серии…" /></label>
        <div className="story-columns"><label className="story-field"><span>Обязательно показать</span><textarea rows={3} value={storyContext.required_events.join("\n")} onChange={(event) => setStoryContext({ ...storyContext, required_events: splitLines(event.target.value) })} placeholder="По одному событию на строку" /></label><label className="story-field"><span>Не включать</span><textarea rows={3} value={storyContext.excluded_events.join("\n")} onChange={(event) => setStoryContext({ ...storyContext, excluded_events: splitLines(event.target.value) })} placeholder="Второстепенные линии или нежелательные сцены" /></label></div>
        <label className="inline-check"><input type="checkbox" checked={storyContext.spoilers_allowed} onChange={(event) => setStoryContext({ ...storyContext, spoilers_allowed: event.target.checked })} /> Можно показывать концовку серии</label>
        <div className="story-actions"><button onClick={saveStoryContext}><Save size={16} /> Сохранить контекст</button><button className="secondary" disabled={isEpisodeBusy(selectedEpisodeId)} onClick={regenerateStoryCandidates}><Sparkles size={16} /> Пересоздать кандидатов</button></div>
        {episodeOutline && <details className="outline-card"><summary>Построенная карта серии</summary><p>{episodeOutline.summary}</p><ol>{episodeOutline.time_ranges.map((item, index) => <li key={`${item.start_time}-${index}`}><strong>{formatClock(item.start_time)}–{formatClock(item.end_time)}</strong> {item.summary}</li>)}</ol></details>}
      </div>
      <div className="panel character-panel"><div className="panel-title"><UserRound size={19} /><h2>Персонажи и голоса</h2><span className="badge">{characters.length}</span></div>
        <div className="character-create"><input value={characterName} onChange={(event) => setCharacterName(event.target.value)} placeholder="Имя персонажа" /><input value={characterDescription} onChange={(event) => setCharacterDescription(event.target.value)} placeholder="Краткое описание" /><label className="file-picker">{characterPhotos.length ? `Выбрано фото: ${characterPhotos.length}` : "Выбрать несколько фото"}<input multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => readCharacterPhotos(event.target.files)} /></label><button disabled={!characterName.trim()} onClick={createCharacter}>Добавить</button></div>
        <div className="character-list">{characters.map((character) => <article className="character-card" key={character.id}><div className="character-photos">{character.photo_urls.map((url, index) => <span className="character-photo" key={url}><img src={url} alt={`${character.name}, фото ${index + 1}`} /><button title="Удалить это фото" onClick={() => deleteCharacterPhoto(character.id, index)}>×</button></span>)}{!character.photo_urls.length && <span className="character-placeholder"><UserRound /></span>}<label className="character-photo-add" title="Добавить фотографии">+<input multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => addCharacterPhotos(character.id, event.target.files)} /></label></div><div className="character-info"><strong>{character.name}</strong><small>{character.description || "Без описания"}</small><small>{character.photo_count} фото · голосовых образцов: {character.voice_sample_count}</small><label className="character-voice" title="Голос закадровой озвучки для арок от лица этого героя"><span>Голос озвучки</span><select value={character.narration_voice ?? ""} onChange={(event) => setCharacterNarrationVoice(character.id, event.target.value || null)}><option value="">Авто ({voiceLabel(character.narration_voice_auto)})</option>{SILERO_VOICES.map((voice) => <option key={voice.id} value={voice.id}>{voice.label}</option>)}</select></label><select title="Объединить дубль в другого персонажа" value="" onChange={(event) => mergeCharacter(character.id, Number(event.target.value))}><option value="">Объединить в…</option>{characters.filter((item) => item.id !== character.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><button className="icon-button danger" title="Удалить персонажа" onClick={() => deleteCharacter(character.id)}><Trash2 size={15} /></button></article>)}{!characters.length && <p className="empty">Добавьте имя и 3–8 фотографий с разными ракурсами. Все файлы останутся на компьютере.</p>}</div>
        {!!speakerLabels.length && <div className="speaker-map"><h3>Кто скрывается за голосами</h3>{speakerLabels.map((label) => { const current = speakerIdentities.find((item) => item.source_label === label); return <label key={label}><span>{label}</span><select value={current?.character_id ?? ""} onChange={(event) => assignSpeaker(label, Number(event.target.value))}><option value="">Не определён</option>{characters.map((character) => <option key={character.id} value={character.id}>{character.name}</option>)}</select>{current && <small>{current.confidence != null ? `${Math.round(current.confidence * 100)}% · ` : ""}{identityMethodLabel(current.method)}</small>}</label>; })}</div>}
        <button className="secondary identify-button" disabled={!characters.some((item) => item.photo_count > 0 || item.voice_sample_count > 0) || isEpisodeBusy(selectedEpisodeId)} onClick={identifyCharacters}><WandSparkles size={16} /> Лица + губы + голоса</button>
      </div>
    </section>}

    {selectedEpisodeId && <section className="workspace section-gap">
      <div className="panel candidate-panel"><div className="panel-title"><Clapperboard size={19} /><h2>Кандидаты</h2>{episodeQuality && <span className="badge">средний score {episodeQuality.average_score}</span>}</div><div className="candidate-toolbar expanded"><label><ListFilter size={16} /><select value={candidateFilter} onChange={(event) => setCandidateFilter(event.target.value as CandidateFilter)}><option value="all">Все статусы</option><option value="new">Новые</option><option value="approved">Принятые</option><option value="rejected">Отклонённые</option><option value="rendered">Готовые</option><option value="problem">С проблемами</option></select></label><select value={candidateSort} onChange={(event) => setCandidateSort(event.target.value as CandidateSort)}><option value="score">Сначала лучшие</option><option value="boundary">Лучшие границы</option><option value="time">По времени</option></select><select value={candidateMomentType} onChange={(event) => setCandidateMomentType(event.target.value)}><option value="all">Все типы</option>{momentTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select><input value={candidateSearch} onChange={(event) => setCandidateSearch(event.target.value)} placeholder="Поиск по смыслу" /><label className="score-filter">Score ≥ <input type="number" min="0" max="100" value={candidateMinScore} onChange={(event) => setCandidateMinScore(Number(event.target.value))} /></label></div>{episodeQuality && <div className="quality-strip"><span>{episodeQuality.transcript_segments} сегм.</span><span>{episodeQuality.scenes} сцен</span><span>{episodeQuality.candidates} кандид.</span><span>{episodeQuality.problem_candidates} с замечаниями</span>{episodeQuality.top_problems.slice(0, 2).map((problem) => <span key={problem}>{problem}</span>)}</div>}
        {selectedEpisodeId && visibleCandidates.length > 0 && <BatchActionBar episodeId={selectedEpisodeId} visibleCandidates={visibleCandidates} selection={batchSelection} busy={isEpisodeBusy(selectedEpisodeId)} onSelectAll={setBatchCandidates} onClear={clearBatchSelection} onReview={batchReviewCandidates} onRender={batchRenderCandidates} />}
        <div className="candidate-list">{visibleCandidates.map((candidate) => { const edit = edits[candidate.id] ?? editFromCandidate(candidate); const busy = isEpisodeBusy(candidate.episode_id); return <article className={`candidate ${selectedCandidate?.id === candidate.id ? "selected" : ""} ${batchSelection.includes(candidate.id) ? "batch-selected" : ""}`} key={candidate.id}><label className="candidate-pick" title="Выбрать для пакетного действия"><input type="checkbox" checked={batchSelection.includes(candidate.id)} onChange={() => toggleBatchCandidate(candidate.id)} /></label><button className="candidate-main" onClick={() => openCandidate(candidate, true)}><span className="score">{candidate.score}</span><span><strong>{candidate.story_order ? `Часть ${candidate.story_order} · ` : ""}{candidate.title}</strong><small>{candidate.story_role ? `${candidate.story_role} · ` : ""}{candidate.moment_type} · {statusLabel(candidate.status)} · {formatRange(candidate.start_time, candidate.end_time)}</small></span><Play size={18} /></button><div className="score-breakdown"><span>Hook {candidate.scores_json.hook ?? "—"}</span><span>Контекст {candidate.scores_json.standalone_context ?? "—"}</span><span>Финал {candidate.scores_json.payoff ?? "—"}</span><span>Границы {candidate.scores_json.boundary_quality ?? "—"}</span></div><p>{candidate.description}</p>{candidate.continuity_note && <small className="continuity-note">Связность: {candidate.continuity_note}</small>}{!!candidate.problems_json.length && <small className="error-text">{candidate.problems_json.join(" · ")}</small>}<div className="compact-edit"><label>Начало<input value={edit.start} onChange={(event) => setCandidateEdit(candidate.id, { start: event.target.value })} /></label><label>Конец<input value={edit.end} onChange={(event) => setCandidateEdit(candidate.id, { end: event.target.value })} /></label><select value={edit.crop} onChange={(event) => chooseCrop(candidate, event.target.value as Candidate["crop_mode"])}><option value="blurred-background">Фон с размытием</option><option value="center-crop">Центр</option><option value="auto-follow">По лицам</option></select></div><div className="candidate-actions"><button disabled={busy} onClick={() => reviewCandidate(candidate, "approve")}><Check size={16} /> Принять</button><button className="secondary" disabled={busy} onClick={() => reviewCandidate(candidate, "reject")}><X size={16} /> Отклонить</button><button className="secondary" disabled={busy || previewBusy} onClick={() => renderPreview(candidate)}><Play size={16} /> Preview</button><button disabled={busy} onClick={() => renderCandidate(candidate, true)}>Рендер с субтитрами</button><button className="secondary" disabled={busy} onClick={() => renderCandidate(candidate, false)}>Без субтитров</button></div></article>; })}{!visibleCandidates.length && <p className="empty">Кандидатов с выбранным фильтром нет.</p>}</div>
      </div>
      <div className="panel editor-panel"><div className="panel-title"><WandSparkles size={19} /><h2>Предпросмотр и редактор</h2></div>{selectedCandidate && selectedEdit ? <>
        <div className={`preview-frame ${selectedEdit.crop}`}><video className="preview-background" ref={backgroundVideoRef} muted src={`/api/episodes/${selectedEpisodeId}/proxy`} /><video className="preview-foreground" ref={videoRef} controls src={`/api/episodes/${selectedEpisodeId}/proxy`} onTimeUpdate={onVideoTimeUpdate} onPlay={() => backgroundVideoRef.current?.play().catch(() => undefined)} onPause={() => backgroundVideoRef.current?.pause()} style={{ objectPosition: `${50 + previewCropOffset(selectedCandidate, selectedEdit, videoTime) * 35}% 50%`, transform: `scale(${selectedEdit.scale})` }} />{activeSubtitle && <div className="subtitle-preview"><small>{activeSubtitle.speaker_label}</small>{activeSubtitle.text}</div>}</div>
        {previewUrl && <video className="render-preview" controls src={previewUrl} />}
        <div className="preview-summary"><strong>{selectedCandidate.title}</strong><span>{formatRange(Number(selectedEdit.start), Number(selectedEdit.end))}</span></div>
        {candidateQuality && <div className="quality-panel"><div className="quality-grid"><span><strong>{candidateQuality.final_score}</strong> score</span><span><strong>{candidateQuality.boundary_score}</strong> границы</span><span><strong>{candidateQuality.standalone_score}</strong> контекст</span><span><strong>{candidateQuality.payoff_score}</strong> финал</span></div>{candidateQuality.recommendations.length ? <ul>{candidateQuality.recommendations.map((item) => <li key={item}>{item}</li>)}</ul> : <small>Критичных замечаний нет.</small>}</div>}
        <KeyframeStrip candidateId={selectedCandidate.id} editRevision={Math.round(selectedCandidate.start_time * 1000) + Math.round(selectedCandidate.end_time)} onSeek={(time) => { const player = videoRef.current; if (player) { player.currentTime = time; } }} />
        <div className="crop-controls"><label>Смещение по горизонтали <span>{selectedEdit.offset.toFixed(2)}</span><input type="range" min="-1" max="1" step="0.02" value={selectedEdit.offset} onChange={(event) => setCandidateEdit(selectedCandidate.id, { offset: Number(event.target.value) })} /></label><label>Масштаб <span>{selectedEdit.scale.toFixed(2)}×</span><input type="range" min="1" max="2" step="0.02" value={selectedEdit.scale} onChange={(event) => setCandidateEdit(selectedCandidate.id, { scale: Number(event.target.value) })} /></label><button disabled={isEpisodeBusy(selectedCandidate.episode_id)} onClick={() => autoCrop(selectedCandidate)}><WandSparkles size={16} /> Найти лица</button></div>
        <CandidateHistory candidateId={selectedCandidate.id} editRevision={Math.round(selectedCandidate.start_time * 1000) + Math.round(selectedCandidate.end_time)} onRestored={() => loadCandidates(selectedCandidate.episode_id, false)} />
        <div className="subtitle-header"><div><h3>Субтитры</h3><small>{subtitleQuality ? `${subtitleQuality.rows} строк · замечаний ${subtitleQuality.warnings.length}` : "Время указано относительно начала клипа."}</small></div><div><button className="secondary" disabled={subtitleBusy || isEpisodeBusy(selectedCandidate.episode_id)} onClick={autoSplitSubtitles}>Разбить</button><button className="icon-button secondary" title="Пересобрать" disabled={subtitleBusy || isEpisodeBusy(selectedCandidate.episode_id)} onClick={resetSubtitles}><RotateCcw size={17} /></button><button onClick={saveSubtitles} disabled={subtitleBusy || isEpisodeBusy(selectedCandidate.episode_id)}><Save size={16} /> Сохранить</button></div></div>
        {subtitleQuality?.warnings.length ? <div className="subtitle-warnings">{subtitleQuality.warnings.slice(0, 4).map((warning) => <small key={warning}>{warning}</small>)}</div> : null}
        <div className="subtitle-list">{subtitles.map((subtitle, index) => <article className="subtitle-row" key={`${subtitle.id ?? "new"}-${index}`}><input type="number" step="0.05" value={subtitle.start_time} onChange={(event) => updateSubtitle(index, { start_time: Number(event.target.value) })} /><input type="number" step="0.05" value={subtitle.end_time} onChange={(event) => updateSubtitle(index, { end_time: Number(event.target.value) })} /><textarea rows={2} value={subtitle.text} onChange={(event) => updateSubtitle(index, { text: event.target.value })} /><select title="Говорящий" value={subtitle.speaker_label ?? ""} onChange={(event) => updateSubtitle(index, { speaker_label: event.target.value || null })}><option value="">Неизвестный</option>{subtitle.speaker_label && !characters.some((item) => item.name === subtitle.speaker_label) && <option value={subtitle.speaker_label}>{subtitle.speaker_label}</option>}{characters.map((character) => <option key={character.id} value={character.name}>{character.name}</option>)}</select><button className="icon-button danger" title="Удалить строку" onClick={() => setSubtitles((current) => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={16} /></button></article>)}</div>
        <button className="secondary add-subtitle" onClick={() => setSubtitles((current) => [...current, { start_time: 0, end_time: 1, text: "Новая строка", speaker_label: null }])}>Добавить строку</button>
      </> : <p className="empty">Нажмите на кандидата, чтобы посмотреть только его отрывок и отредактировать кадр и субтитры.</p>}</div>
    </section>}

    <section className="panel section-gap workflow-panel"><div className="panel-title"><Activity size={19} /><h2>Workflow сезона</h2><button className="icon-button secondary" title="Диагностика проекта" onClick={refreshProjectDiagnostics}><RefreshCcw size={17} /></button></div>
      <div className="workflow-grid">
        <div className="workflow-block"><h3>Поиск</h3><div className="search-row"><input value={seasonSearch} onChange={(event) => setSeasonSearch(event.target.value)} placeholder="Найти сцену, реплику или событие по сезону" /><button disabled={!arcSeason || !seasonSearch.trim()} onClick={runSeasonSearch}><Search size={16} /> Найти</button></div><div className="search-results">{searchResults.slice(0, 6).map((result) => <article key={`${result.kind}-${result.episode_id}-${result.start_time}`}><div><strong>{result.title}</strong><small>{result.episode_file_name} · {formatRange(result.start_time, result.end_time)} · score {result.score}</small></div><p>{result.snippet}</p>{workflowArc && result.candidate_id && <button className="text-button" onClick={() => addSearchResultToArc(workflowArc, result)}>Добавить в StoryArc</button>}</article>)}{!searchResults.length && <small>Поиск работает по кандидатам и транскриптам выбранного сезона.</small>}</div></div>
        <div className="workflow-block">
          <h3>StoryArc редактор</h3>
          {workflowArc ? <>
            <label className="setting-field">
              <span>План</span>
              <select value={workflowArc.id} onChange={(event) => setWorkflowArcId(Number(event.target.value))}>
                {visibleStoryArcs.map((arc) => <option key={arc.id} value={arc.id}>{arc.title}</option>)}
              </select>
              <small>{workflowArc.segments.length} частей · {formatElapsed(Math.round(workflowArc.total_duration_seconds))}</small>
            </label>
            <div className="arc-edit-row">
              <input value={workflowArc.title} onChange={(event) => patchArcLocal(workflowArc.id, { title: event.target.value })} />
              <select value={workflowArc.output_format} onChange={(event) => patchArcLocal(workflowArc.id, { output_format: event.target.value as StoryArc["output_format"] })}>
                <option value="single_short">Один Shorts</option>
                <option value="shorts_series">Серия Shorts</option>
                <option value="story_video">Видео 2–10 мин</option>
                <option value="long_video">Длинное видео</option>
              </select>
              <button onClick={() => saveArcMeta(workflowArc)}><Save size={16} /> Сохранить</button>
            </div>
            <label className="setting-field">
              <span>Переходы</span>
              <select value={arcTransition} onChange={(event) => setArcTransition(event.target.value as "cut" | "fade")}>
                <option value="fade">Fade</option>
                <option value="cut">Склейка без перехода</option>
              </select>
              <small>Применяется при StoryArc-рендере.</small>
            </label>
            <SettingCheck title="Добавлять озвучку" hint="Локальная озвучка смешивается с приглушённым звуком оригинала." checked={arcIncludeNarration} onChange={setArcIncludeNarration} />
            <label className="setting-field">
              <span>Режим озвучки</span>
              <select value={arcNarrationMode} onChange={(event) => { const mode = event.target.value as "first_person" | "narrator" | "none"; setArcNarrationMode(mode); setArcIncludeNarration(mode !== "none"); }}>
                <option value="first_person">От лица героя</option>
                <option value="narrator">Нейтральный диктор</option>
                <option value="none">Без озвучки</option>
              </select>
              <small>Это локальный TTS, не имитация голоса актёра.</small>
            </label>
            <div className="arc-actions">
              <button disabled={arcRenderBusy === workflowArc.id || !workflowArc.segments.length} onClick={() => enqueueStoryArcRender(workflowArc, true)}><Clapperboard size={16} /> В очередь</button>
              <button className="secondary" disabled={arcRenderBusy === workflowArc.id || !workflowArc.segments.length} onClick={() => renderStoryArc(workflowArc, false)}>Без субтитров</button>
              <button className="secondary" onClick={() => synthesizeNarration(workflowArc)}><Volume2 size={16} /> WAV</button>
            </div>
          </> : <p className="empty">Создайте StoryArc, чтобы редактировать сезонный монтаж.</p>}
        </div>
        <div className="workflow-block workflow-wide"><h3>Сегменты</h3>{workflowArc ? <div className="segment-editor">{workflowArc.segments.map((segment) => <article key={segment.id}><div className="segment-row"><button className="icon-button secondary" title="Выше" onClick={() => moveArcSegment(workflowArc.id, segment, -1)}>↑</button><button className="icon-button secondary" title="Ниже" onClick={() => moveArcSegment(workflowArc.id, segment, 1)}>↓</button><input type="number" min="0" step="0.1" value={segment.start_time} onChange={(event) => patchArcSegmentLocal(workflowArc.id, segment.id, { start_time: Number(event.target.value) })} /><input type="number" min="0" step="0.1" value={segment.end_time} onChange={(event) => patchArcSegmentLocal(workflowArc.id, segment.id, { end_time: Number(event.target.value) })} /><input value={segment.title} onChange={(event) => patchArcSegmentLocal(workflowArc.id, segment.id, { title: event.target.value })} /><input value={segment.role ?? ""} onChange={(event) => patchArcSegmentLocal(workflowArc.id, segment.id, { role: event.target.value || null })} /><button onClick={() => saveArcSegment(workflowArc.id, segment)}><Save size={16} /></button><button className="icon-button danger" title="Удалить" onClick={() => removeArcSegment(workflowArc.id, segment.id)}><Trash2 size={16} /></button></div><small>{segment.episode_file_name} · {segment.note}</small></article>)}</div> : <p className="empty">Сегменты появятся после создания плана.</p>}</div>
        <div className="workflow-block"><h3>Сценарий</h3>{workflowArc ? <><textarea rows={3} value={scriptPrompt} onChange={(event) => setScriptPrompt(event.target.value)} placeholder="Акцент для сценария: конфликт, развитие героя, быстрый пересказ…" /><button onClick={() => createVideoScriptForArc(workflowArc)}><FileText size={16} /> Создать сценарий</button></> : <small>Нужен StoryArc.</small>}<div className="script-list">{workflowScripts.map((script) => <details key={script.id}><summary>{script.title}</summary><pre>{script.script_text}</pre></details>)}</div></div>
        <div className="workflow-block"><h3>Публикация</h3>{workflowArc ? <button onClick={() => createPublishingPlanForArc(workflowArc)}><CalendarDays size={16} /> Создать план</button> : <small>Нужен StoryArc.</small>}<div className="publishing-list">{workflowPublishing.map((plan) => <article key={plan.id}><strong>{plan.title}</strong><small>{plan.platform} · {statusLabel(plan.status)}</small><p>{plan.description}</p><small>{plan.hashtags.join(" ")}</small><button className="text-button" disabled={!plan.story_arc_export_id} onClick={() => createPublishingPackageForPlan(plan)}>Собрать publishing.json</button></article>)}</div></div>
        <div className="workflow-block"><h3>Диагностика</h3><div className="checks compact">{projectDiagnostics?.checks.map((item) => <div className="check" key={item.name}><span className={item.ok ? "dot ok" : "dot fail"} /><strong>{item.name}</strong><span>{item.message}</span></div>)}</div>{projectDiagnostics?.recommendations.map((item) => <small className="warn-text" key={item}>{item}</small>)}</div>
      </div>
    </section>

    <ExportsPanel exports={exports} />

    <section className="grid section-gap">
      <SystemPanel checks={checks} diagnostics={diagnostics} cacheInfo={cacheInfo} onRefresh={runSystemCheck} onClearCache={clearCache} />
      <SettingsPanel settings={settings} onPatch={patchSettings} onSave={saveSettings} />
    </section>

    <section className="grid section-gap">
      <ModelCatalogPanel />
      <LogViewerPanel />
    </section>
  </main>;
}
