import { Check, Clapperboard, ListFilter, Play, RotateCcw, Save, Trash2, WandSparkles, X } from "lucide-react";

import type { CandidateFilter, CandidateSort } from "../hooks/useCandidates";
import type { SerialCutsController } from "../hooks/useSerialCutsController";
import type { Candidate } from "../types";
import { editFromCandidate, formatRange, statusLabel } from "../utils";
import { BatchActionBar } from "./BatchActionBar";
import { CandidateHistory } from "./CandidateHistory";
import { FramedPreview } from "./FramedPreview";
import { KeyframeStrip } from "./KeyframeStrip";

type CandidateWorkspaceSectionProps = {
  controller: SerialCutsController;
};

/** Candidate list (filters, batch actions) on the left, the open candidate's editor/preview on the right. */
export function CandidateWorkspaceSection({ controller }: CandidateWorkspaceSectionProps) {
  const {
    selectedEpisodeId, episodeQuality, candidateFilter, setCandidateFilter, candidateSort, setCandidateSort,
    candidateMomentType, setCandidateMomentType, momentTypes, candidateSearch, setCandidateSearch,
    candidateMinScore, setCandidateMinScore, visibleCandidates, batchSelection, isEpisodeBusy,
    setBatchCandidates, clearBatchSelection, batchReviewCandidates, batchRenderCandidates,
    edits, selectedCandidate, toggleBatchCandidate, openCandidate, setCandidateEdit, chooseCrop, reviewCandidate,
    previewBusy, renderPreview, renderCandidate, selectedEdit, videoTime, activeSubtitle, videoRef, backgroundVideoRef,
    onVideoTimeUpdate, previewUrl, candidateQuality, autoCrop, loadCandidates, subtitleQuality, subtitleBusy,
    autoSplitSubtitles, resetSubtitles, saveSubtitles, subtitles, characters, updateSubtitle, setSubtitles,
  } = controller;

  if (!selectedEpisodeId) return null;

  return <section className="workspace section-gap">
    <div className="panel candidate-panel"><div className="panel-title"><Clapperboard size={19} /><h2>Кандидаты</h2>{episodeQuality && <span className="badge">средний score {episodeQuality.average_score}</span>}</div><div className="candidate-toolbar expanded"><label><ListFilter size={16} /><select value={candidateFilter} onChange={(event) => setCandidateFilter(event.target.value as CandidateFilter)}><option value="all">Все статусы</option><option value="new">Новые</option><option value="approved">Принятые</option><option value="rejected">Отклонённые</option><option value="rendered">Готовые</option><option value="problem">С проблемами</option></select></label><select value={candidateSort} onChange={(event) => setCandidateSort(event.target.value as CandidateSort)}><option value="score">Сначала лучшие</option><option value="boundary">Лучшие границы</option><option value="time">По времени</option></select><select value={candidateMomentType} onChange={(event) => setCandidateMomentType(event.target.value)}><option value="all">Все типы</option>{momentTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select><input value={candidateSearch} onChange={(event) => setCandidateSearch(event.target.value)} placeholder="Поиск по смыслу" /><label className="score-filter">Score ≥ <input type="number" min="0" max="100" value={candidateMinScore} onChange={(event) => setCandidateMinScore(Number(event.target.value))} /></label></div>{episodeQuality && <div className="quality-strip"><span>{episodeQuality.transcript_segments} сегм.</span><span>{episodeQuality.scenes} сцен</span><span>{episodeQuality.candidates} кандид.</span><span>{episodeQuality.problem_candidates} с замечаниями</span>{episodeQuality.top_problems.slice(0, 2).map((problem) => <span key={problem}>{problem}</span>)}{(episodeQuality.media_warnings ?? []).map((w) => <span key={w} className="warn-text">⚠ {w}</span>)}</div>}
      {selectedEpisodeId && visibleCandidates.length > 0 && <BatchActionBar episodeId={selectedEpisodeId} visibleCandidates={visibleCandidates} selection={batchSelection} busy={isEpisodeBusy(selectedEpisodeId)} onSelectAll={setBatchCandidates} onClear={clearBatchSelection} onReview={batchReviewCandidates} onRender={batchRenderCandidates} />}
      <div className="candidate-list">{visibleCandidates.map((candidate) => { const edit = edits[candidate.id] ?? editFromCandidate(candidate); const busy = isEpisodeBusy(candidate.episode_id); return <article className={`candidate ${selectedCandidate?.id === candidate.id ? "selected" : ""} ${batchSelection.includes(candidate.id) ? "batch-selected" : ""}`} key={candidate.id}><label className="candidate-pick" title="Выбрать для пакетного действия"><input type="checkbox" checked={batchSelection.includes(candidate.id)} onChange={() => toggleBatchCandidate(candidate.id)} /></label><button className="candidate-main" onClick={() => openCandidate(candidate, true)}><span className="score">{candidate.score}</span><span><strong>{candidate.story_order ? `Часть ${candidate.story_order} · ` : ""}{candidate.title}</strong><small>{candidate.story_role ? `${candidate.story_role} · ` : ""}{candidate.moment_type} · {statusLabel(candidate.status)} · {formatRange(candidate.start_time, candidate.end_time)}</small></span><Play size={18} /></button><div className="score-breakdown"><span>Hook {candidate.scores_json.hook ?? "—"}</span><span>Контекст {candidate.scores_json.standalone_context ?? "—"}</span><span>Финал {candidate.scores_json.payoff ?? "—"}</span><span>Границы {candidate.scores_json.boundary_quality ?? "—"}</span></div><p>{candidate.description}</p>{candidate.continuity_note && <small className="continuity-note">Связность: {candidate.continuity_note}</small>}{!!candidate.problems_json.length && <small className="error-text">{candidate.problems_json.join(" · ")}</small>}<div className="compact-edit"><label>Начало<input value={edit.start} onChange={(event) => setCandidateEdit(candidate.id, { start: event.target.value })} /></label><label>Конец<input value={edit.end} onChange={(event) => setCandidateEdit(candidate.id, { end: event.target.value })} /></label><select aria-label="Кадрирование" value={edit.crop} onChange={(event) => chooseCrop(candidate, event.target.value as Candidate["crop_mode"])}><option value="center-crop">Центр</option><option value="auto-follow">По лицу</option><option value="split">Split (два спикера)</option></select></div><div className="candidate-actions"><button disabled={busy} onClick={() => reviewCandidate(candidate, "approve")}><Check size={16} /> Принять</button><button className="secondary" disabled={busy} onClick={() => reviewCandidate(candidate, "reject")}><X size={16} /> Отклонить</button><button className="secondary" disabled={busy || previewBusy} onClick={() => renderPreview(candidate)}><Play size={16} /> Preview</button><button disabled={busy} onClick={() => renderCandidate(candidate, true)}>Рендер с субтитрами</button><button className="secondary" disabled={busy} onClick={() => renderCandidate(candidate, false)}>Без субтитров</button></div></article>; })}{!visibleCandidates.length && <p className="empty">Кандидатов с выбранным фильтром нет.</p>}</div>
    </div>
    <div className="panel editor-panel"><div className="panel-title"><WandSparkles size={19} /><h2>Предпросмотр и редактор</h2></div>{selectedCandidate && selectedEdit ? <>
      <FramedPreview candidate={selectedCandidate} edit={selectedEdit} videoTime={videoTime} subtitle={activeSubtitle} videoRef={videoRef} backgroundRef={backgroundVideoRef} onTimeUpdate={onVideoTimeUpdate} />
      <p className="framing-hint">Крупное видео в центре, мягкий фон сверху и снизу. «По лицу» меняет положение кадра, сохраняя этот размер.</p>
      {previewUrl && <video className="render-preview" controls src={previewUrl} />}
      <div className="preview-summary"><strong>{selectedCandidate.title}</strong><span>{formatRange(Number(selectedEdit.start), Number(selectedEdit.end))}</span></div>
      {candidateQuality && <div className="quality-panel"><div className="quality-grid"><span><strong>{candidateQuality.final_score}</strong> score</span><span><strong>{candidateQuality.boundary_score}</strong> границы</span><span><strong>{candidateQuality.standalone_score}</strong> контекст</span><span><strong>{candidateQuality.payoff_score}</strong> финал</span></div>{candidateQuality.recommendations.length ? <ul>{candidateQuality.recommendations.map((item) => <li key={item}>{item}</li>)}</ul> : <small>Критичных замечаний нет.</small>}</div>}
      <KeyframeStrip candidateId={selectedCandidate.id} editRevision={Math.round(selectedCandidate.start_time * 1000) + Math.round(selectedCandidate.end_time)} onSeek={(time) => { const player = videoRef.current; if (player) { player.currentTime = time; } }} />
      <div className="crop-controls"><label>Смещение по горизонтали <span>{selectedEdit.offset.toFixed(2)}</span><input type="range" min="-1" max="1" step="0.02" value={selectedEdit.offset} onChange={(event) => setCandidateEdit(selectedCandidate.id, { offset: Number(event.target.value) })} /></label><label>Приближение внутри кадра <span>{selectedEdit.scale.toFixed(2)}×</span><input type="range" min="1" max="2" step="0.02" value={selectedEdit.scale} onChange={(event) => setCandidateEdit(selectedCandidate.id, { scale: Number(event.target.value) })} /></label><button disabled={isEpisodeBusy(selectedCandidate.episode_id)} onClick={() => autoCrop(selectedCandidate)}><WandSparkles size={16} /> Найти лица</button></div>
      <CandidateHistory candidateId={selectedCandidate.id} editRevision={Math.round(selectedCandidate.start_time * 1000) + Math.round(selectedCandidate.end_time)} onRestored={() => loadCandidates(selectedCandidate.episode_id, false)} />
      <div className="subtitle-header"><div><h3>Субтитры</h3><small>{subtitleQuality ? `${subtitleQuality.rows} строк · замечаний ${subtitleQuality.warnings.length}` : "Время указано относительно начала клипа."}</small></div><div><button className="secondary" disabled={subtitleBusy || isEpisodeBusy(selectedCandidate.episode_id)} onClick={autoSplitSubtitles}>Разбить</button><button className="icon-button secondary" title="Пересобрать" disabled={subtitleBusy || isEpisodeBusy(selectedCandidate.episode_id)} onClick={resetSubtitles}><RotateCcw size={17} /></button><button onClick={saveSubtitles} disabled={subtitleBusy || isEpisodeBusy(selectedCandidate.episode_id)}><Save size={16} /> Сохранить</button></div></div>
      {subtitleQuality?.warnings.length ? <div className="subtitle-warnings">{subtitleQuality.warnings.slice(0, 4).map((warning) => <small key={warning}>{warning}</small>)}</div> : null}
      <div className="subtitle-list">{subtitles.map((subtitle, index) => <article className="subtitle-row" key={`${subtitle.id ?? "new"}-${index}`}><input type="number" step="0.05" value={subtitle.start_time} onChange={(event) => updateSubtitle(index, { start_time: Number(event.target.value) })} /><input type="number" step="0.05" value={subtitle.end_time} onChange={(event) => updateSubtitle(index, { end_time: Number(event.target.value) })} /><textarea rows={2} value={subtitle.text} onChange={(event) => updateSubtitle(index, { text: event.target.value })} /><select title="Говорящий" value={subtitle.speaker_label ?? ""} onChange={(event) => updateSubtitle(index, { speaker_label: event.target.value || null })}><option value="">Неизвестный</option>{subtitle.speaker_label && !characters.some((item) => item.name === subtitle.speaker_label) && <option value={subtitle.speaker_label}>{subtitle.speaker_label}</option>}{characters.map((character) => <option key={character.id} value={character.name}>{character.name}</option>)}</select><button className="icon-button danger" title="Удалить строку" onClick={() => setSubtitles((current) => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={16} /></button></article>)}</div>
      <button className="secondary add-subtitle" onClick={() => setSubtitles((current) => [...current, { start_time: 0, end_time: 1, text: "Новая строка", speaker_label: null }])}>Добавить строку</button>
    </> : <p className="empty">Нажмите на кандидата, чтобы посмотреть только его отрывок и отредактировать кадр и субтитры.</p>}</div>
  </section>;
}
