import { Save, Server } from "lucide-react";
import type { RuntimeSettings } from "../types";
import { SettingCheck, SettingNumber, SettingText } from "./SettingsFields";

type Props = {
  settings: RuntimeSettings | null;
  onPatch: (patch: Partial<RuntimeSettings>) => void;
  onSave: () => void;
};

export function SettingsPanel({ settings, onPatch, onSave }: Props) {
  return <div className="panel"><div className="panel-title"><Server size={19} /><h2>Настройки</h2></div>{settings && <div className="settings-sections">
    <section className="settings-section"><h3>Файлы</h3><div className="settings-grid"><SettingText title="Папка временных файлов" hint="Proxy, WAV и промежуточные данные; их можно безопасно удалить." value={settings.cache_dir} onChange={(value) => onPatch({ cache_dir: value })} wide /><SettingText title="Папка готовых роликов" hint="Готовые MP4, обложки, субтитры и метаданные." value={settings.output_dir} onChange={(value) => onPatch({ output_dir: value })} wide /></div></section>
    <section className="settings-section"><h3>Анализ и Auto</h3><div className="settings-grid"><label className="setting-field"><span>Профиль качества</span><select value={settings.quality_profile} onChange={(event) => onPatch({ quality_profile: event.target.value as RuntimeSettings["quality_profile"] })}><option value="fast">Быстрый</option><option value="balanced">Сбалансированный</option><option value="quality">Качественный</option></select><small>Баланс скорости и тщательности локального анализа.</small></label><SettingNumber title="Минимальная длина, сек." hint="Короткий кандидат будет расширен." value={settings.min_clip_seconds} min={5} max={300} onChange={(value) => onPatch({ min_clip_seconds: value })} /><SettingNumber title="Максимальная длина, сек." hint="Клип не выйдет за этот предел." value={settings.max_clip_seconds} min={5} max={300} onChange={(value) => onPatch({ max_clip_seconds: value })} /><SettingNumber title="Порог Auto, баллы" hint="Auto принимает кандидатов с этой оценкой и выше." value={settings.auto_score_threshold} min={0} max={100} onChange={(value) => onPatch({ auto_score_threshold: value })} /><SettingNumber title="Максимум клипов" hint="Лимит автоматического экспорта из серии." value={settings.max_clips_per_episode} min={1} max={20} onChange={(value) => onPatch({ max_clips_per_episode: value })} /><SettingCheck title="Фоновая очередь" hint="Новые задачи запускаются сами." checked={settings.background_queue_enabled} onChange={(value) => onPatch({ background_queue_enabled: value })} /><SettingCheck title="Auto по умолчанию" hint="Лучшие кандидаты принимаются и экспортируются." checked={settings.auto_mode_enabled} onChange={(value) => onPatch({ auto_mode_enabled: value })} /></div></section>
    <section className="settings-section"><h3>Рендер и субтитры</h3><div className="settings-grid"><label className="setting-field"><span>Платформа</span><select value={settings.render_preset} onChange={(event) => onPatch({ render_preset: event.target.value as RuntimeSettings["render_preset"] })}><option value="youtube_shorts">YouTube Shorts</option><option value="instagram_reels">Instagram Reels</option></select><small>Битрейт и параметры MP4.</small></label><SettingText title="Шрифт субтитров" hint="Шрифт, установленный в Windows." value={settings.subtitle_font_name} onChange={(value) => onPatch({ subtitle_font_name: value })} /><SettingNumber title="Размер субтитров" hint="Обычно 36–52 для вертикального кадра." value={settings.subtitle_font_size} min={24} max={96} onChange={(value) => onPatch({ subtitle_font_size: value })} /><label className="setting-field"><span>Safe zone субтитров</span><select value={settings.subtitle_safe_zone} onChange={(event) => onPatch({ subtitle_safe_zone: event.target.value as RuntimeSettings["subtitle_safe_zone"] })}><option value="shorts">YouTube Shorts</option><option value="reels">Instagram Reels</option><option value="high">Выше интерфейса</option><option value="standard">Стандарт</option></select><small>Поднимает текст выше кнопок и описания платформы.</small></label><SettingCheck title="Показывать имя персонажа" hint="Добавляет имя говорящего над текстом в готовом видео." checked={settings.subtitle_show_speaker_names} onChange={(value) => onPatch({ subtitle_show_speaker_names: value })} /><SettingCheck title="NVIDIA NVENC" hint="Ускоряет рендер; при ошибке включится CPU." checked={settings.render_use_nvenc} onChange={(value) => onPatch({ render_use_nvenc: value })} /><SettingCheck title="Точная громкость" hint="Два прохода: медленнее, но ровнее звук." checked={settings.render_loudnorm_two_pass} onChange={(value) => onPatch({ render_loudnorm_two_pass: value })} /><SettingText title="Шаблон имени файла" hint="{episode}, {candidate}, {title}, {score}, {moment_type}, {start}, {end}" value={settings.export_filename_template} onChange={(value) => onPatch({ export_filename_template: value })} wide /></div></section>
    <button className="settings-save" onClick={onSave}><Save size={17} /> Сохранить настройки</button>
  </div>}</div>;
}
