export type Episode = { id: number; file_name: string; file_path: string; stage: string; size_bytes: number; duration_seconds: number | null; width: number | null; height: number | null; fps: number | null };
export type Season = { id: number; title: string; root_path: string; episodes: Episode[] };
export type CheckItem = { name: string; ok: boolean; message: string };
export type Job = { id: number; episode_id: number | null; kind: string; status: string; current_stage: string | null; progress: number; progress_message: string | null; error_message: string | null; started_at: string | null; finished_at: string | null; created_at: string; updated_at: string };
export type QueueData = { snapshot: { queued: number; running: number; failed: number; paused: boolean; eta_seconds: number | null }; items: Job[] };
export type RuntimeSettings = {
  cache_dir: string; output_dir: string; quality_profile: "fast" | "balanced" | "quality";
  min_clip_seconds: number; max_clip_seconds: number; auto_mode_enabled: boolean; background_queue_enabled: boolean;
  auto_score_threshold: number; max_clips_per_episode: number; render_preset: "youtube_shorts" | "instagram_reels";
  render_use_nvenc: boolean; render_loudnorm_two_pass: boolean; subtitle_font_name: string; subtitle_font_size: number;
  subtitle_safe_zone: "standard" | "shorts" | "reels" | "high"; subtitle_show_speaker_names: boolean; export_filename_template: string;
  tts_adapter: "windows-sapi" | "silero" | "stub"; tts_narrator_voice: string;
  asr_adapter: "stub" | "faster-whisper"; llm_adapter: "stub" | "llama-cpp-http"; llm_base_url: string;
};
export type TtsVoice = { id: string; label: string; gender: string };
export type TtsVoiceCatalog = { adapter: string; voices: TtsVoice[] };
export type Candidate = {
  id: number; episode_id: number; start_time: number; end_time: number; title: string; description: string;
  moment_type: string; score: number; scores_json: Record<string, number>; rationale: string; problems_json: string[];
  crop_mode: "auto-follow" | "center-crop" | "blurred-background" | "split"; crop_offset_x: number; crop_scale: number;
  thumbnail_path: string | null; status: string; story_order: number | null; story_role: string | null; continuity_note: string | null;
  crop_keyframes_json: { time: number; offset: number }[];
};
export type CandidateEdit = { start: string; end: string; crop: Candidate["crop_mode"]; offset: number; scale: number };
export type Subtitle = { id?: number | null; start_time: number; end_time: number; text: string; speaker_label?: string | null };
export type ExportItem = { id: number; candidate_id: number; output_path: string; cover_path: string | null; include_subtitles: boolean; preset_name: string; status: string; version: number; render_fingerprint: string | null };
export type ModelDiagnostics = { asr_adapter: string; asr_ready: boolean; asr_model: string; asr_device: string; asr_compute_type: string; asr_package_installed: boolean; asr_local_model_path: string | null; asr_local_model_exists: boolean; llm_adapter: string; llm_ready: boolean; llm_url: string; llm_model_hint: string; llm_latency_ms: number | null; tts_adapter: string; tts_ready: boolean; tts_model_path: string; tts_model_exists: boolean; tts_torch_installed: boolean; tts_narrator_voice: string; face_ready: boolean; face_model: string; face_detector_path: string; face_recognizer_path: string; face_detector_exists: boolean; face_recognizer_exists: boolean; details: string[]; recommendations: string[] };
export type CacheInfo = { cache_dir: string; files: number; bytes: number };
export type CandidateQuality = { candidate_id: number; duration_seconds: number; final_score: number; boundary_score: number; standalone_score: number; payoff_score: number; audio_score: number; visual_score: number; problems: string[]; recommendations: string[] };
export type EpisodeQuality = { episode_id: number; stage: string; transcript_segments: number; words: number; scenes: number; candidates: number; approved: number; rejected: number; rendered: number; average_score: number; problem_candidates: number; top_problems: string[]; media_warnings: string[] };
export type SubtitleQuality = { candidate_id: number; rows: number; warnings: string[]; long_rows: number; overlaps: number; too_fast_rows: number };
export type JobStage = { id: number; job_id: number; name: string; status: string; started_at: string | null; finished_at: string | null; error_message: string | null; artifact_path: string | null };
export type PreviewRender = { candidate_id: number; output_path: string; preview_url: string; duration_seconds: number };
export type BlockingProgress = { kind: "media" | "candidates"; episodeId: number; fileName: string; startedAt: number };
export type StoryContext = { season_id: number; episode_id: number; season_context: string; episode_summary: string; required_events: string[]; excluded_events: string[]; spoilers_allowed: boolean; candidate_mode: "highlights" | "story" };
export type StoryArcSegment = { id: number; story_arc_id: number; episode_id: number; episode_file_name: string; candidate_id: number | null; candidate_score: number | null; sort_order: number; start_time: number; end_time: number; title: string; note: string; role: string | null };
export type StoryArcExport = { id: number; story_arc_id: number; output_path: string; metadata_path: string | null; cover_path: string | null; width: number; height: number; include_subtitles: boolean; preset_name: string; segment_count: number; status: string; transition_style: string; narration_included: boolean; version: number; render_fingerprint: string | null };
export type StoryArc = { id: number; season_id: number; season_title: string; title: string; prompt: string; arc_type: "custom" | "character" | "story_arc"; output_format: "single_short" | "shorts_series" | "story_video" | "long_video"; target_character_id: number | null; target_character_name: string | null; status: string; total_duration_seconds: number; plan_json: Record<string, unknown>; segments: StoryArcSegment[]; exports: StoryArcExport[] };
export type SearchResult = { kind: string; episode_id: number; episode_file_name: string; candidate_id: number | null; start_time: number; end_time: number; title: string; snippet: string; score: number };
export type VideoScript = { id: number; season_id: number; story_arc_id: number | null; title: string; prompt: string; style: string; script_text: string; structure_json: Record<string, unknown>; status: string };
export type PublishingPlan = { id: number; season_id: number; story_arc_id: number | null; story_arc_export_id: number | null; platform: string; title: string; description: string; hashtags: string[]; scheduled_for: string | null; status: string };
export type ProjectDiagnostics = { checks: CheckItem[]; recommendations: string[]; counts: Record<string, number> };
export type Character = { id: number; season_id: number; name: string; description: string; aliases: string[]; color: string; photo_count: number; photo_urls: string[]; voice_sample_count: number; narration_voice: string | null; narration_voice_auto: string | null };
export type SpeakerIdentity = { source_label: string; character_id: number; character_name: string; confidence: number | null; method: string };
export type EpisodeOutline = { summary: string; main_events: string[]; conflicts: string[]; time_ranges: { start_time: number; end_time: number; summary: string }[] };
export type Health = { ok: boolean; service: string; version: string; commit: string | null; boot_id: string; token_fingerprint: string; started_at: string; uptime_seconds: number; db_revision: string | null; queue: { state: string; queued: number; running: number; failed: number } };
export type LogEntry = { timestamp: string | null; level: string; logger: string; message: string };
export type LogTail = { path: string; exists: boolean; size_bytes: number; returned: number; entries: LogEntry[] };
export type ModelCatalogEntry = { key: string; title: string; purpose: string; approx_size_mb: number; target_dir: string; installed: boolean; files_present: string[]; files_missing: string[]; installable_in_app: boolean; install_command: string };
export type ModelInstallProgress = { key: string; status: "idle" | "running" | "done" | "error"; received_bytes: number; total_bytes: number; detail: string };
export type CandidateSnapshot = { id: number; candidate_id: number; edit_revision: number; kind: string; label: string; created_at: string; start_time: number; end_time: number; crop_mode: string; subtitle_rows: number };
export type KeyframeStripData = { candidate_id: number; edit_revision: number; start_time: number; end_time: number; frames: { index: number; time: number; url: string }[] };
export type BatchOutcome = { requested: number; succeeded: number[]; skipped: { candidate_id: number; reason: string }[]; job_ids: number[] };
export type ImportResult = { season_id: number; created: number; skipped_duplicates: number; episode_ids: number[]; scanned: number; errors: { file_name: string; reason: string }[] };
